// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/ingest/benchmarks": {
            "post": {
                "description": "Fetches daily data for configured benchmarks (e.g., SPY) from SHARADAR/DAILY",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingestion"
                ],
                "summary": "Ingest benchmark prices",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Fetch all history (default: incremental)",
                        "name": "full",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.IngestResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.IngestResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.IngestResponse"
                        }
                    }
                }
            }
        },
        "/admin/ingest/daily": {
            "post": {
                "description": "Fetches daily price/fundamental data from SHARADAR/DAILY. If no ticker specified, fetches for all DB companies.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingestion"
                ],
                "summary": "Ingest daily prices",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comma-separated tickers (defaults to all companies in DB)",
                        "name": "ticker",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Fetch all history (default: incremental)",
                        "name": "full",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.IngestResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.IngestResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.IngestResponse"
                        }
                    }
                }
            }
        },
        "/admin/ingest/fundamentals": {
            "post": {
                "description": "Fetches fundamental data from SHARADAR/SF1 and upserts into financial_metrics table",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingestion"
                ],
                "summary": "Ingest financial metrics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comma-separated tickers (defaults to all companies in DB)",
                        "name": "ticker",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "ARQ,MRQ",
                        "description": "Comma-separated dimensions",
                        "name": "dimension",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Fetch all history (default: incremental)",
                        "name": "full",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.IngestResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.IngestResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.IngestResponse"
                        }
                    }
                }
            }
        },
        "/admin/ingest/status": {
            "get": {
                "description": "Returns current data counts and last update timestamps",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingestion"
                ],
                "summary": "Get ingestion status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/admin/ingest/tickers": {
            "post": {
                "description": "Fetches company metadata from SHARADAR/TICKERS and upserts into the companies table",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ingestion"
                ],
                "summary": "Ingest company tickers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comma-separated tickers (defaults to all)",
                        "name": "ticker",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.IngestResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handlers.IngestResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the health status of the application",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_handlers.IngestResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "elapsed": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "DeepValue API",
	Description:      "Personal value investing portfolio manager API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
