// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Layout(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\" class=\"mocha\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/views/layout.templ`, Line: 9, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " | DeepValue</title><link rel=\"icon\" type=\"image/png\" href=\"/assets/favicon.png\"><link rel=\"stylesheet\" href=\"/assets/css/output.css\"><script src=\"https://unpkg.com/htmx.org@2.0.4\"></script><script>\n\t\t\t\t// Apply saved theme before render to avoid flash\n\t\t\t\t(function() {\n\t\t\t\t\tconst theme = localStorage.getItem('theme') || 'mocha';\n\t\t\t\t\tdocument.documentElement.className = theme;\n\t\t\t\t})();\n\t\t\t</script></head><body class=\"bg-ctp-base text-ctp-text min-h-screen transition-colors duration-200\"><nav class=\"bg-ctp-mantle border-b border-ctp-surface0 px-6 py-4\"><div class=\"max-w-7xl mx-auto flex items-center justify-between\"><a href=\"/\" class=\"flex items-center gap-2\"><img src=\"/assets/mascot.png\" alt=\"DeepValue\" class=\"w-8 h-8 rounded-full\"> <span class=\"text-xl font-bold text-ctp-lavender\">DeepValue</span></a><div class=\"flex items-center gap-4\"><a href=\"/\" class=\"text-ctp-subtext1 hover:text-ctp-text transition-colors\">Dashboard</a> <a href=\"/portfolio\" class=\"text-ctp-subtext1 hover:text-ctp-text transition-colors\">Portfolio</a> <a href=\"/backtest\" class=\"text-ctp-subtext1 hover:text-ctp-text transition-colors\">Backtest</a> <select id=\"theme-select\" class=\"bg-ctp-surface0 text-ctp-text border border-ctp-surface1 rounded px-2 py-1 text-sm focus:outline-none focus:border-ctp-lavender\" onchange=\"setTheme(this.value)\"><option value=\"latte\">Latte</option> <option value=\"frappe\">Frappe</option> <option value=\"macchiato\">Macchiato</option> <option value=\"mocha\">Mocha</option></select></div></div></nav><main class=\"max-w-7xl mx-auto px-6 py-8\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</main><script>\n\t\t\t\tfunction setTheme(theme) {\n\t\t\t\t\tdocument.documentElement.className = theme;\n\t\t\t\t\tlocalStorage.setItem('theme', theme);\n\t\t\t\t}\n\t\t\t\t// Set dropdown to current theme on load\n\t\t\t\tdocument.getElementById('theme-select').value = localStorage.getItem('theme') || 'mocha';\n\t\t\t</script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
